name: Forge
options:
  bundleIdPrefix: com.iroralabs
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGN_ENTITLEMENTS: ""

packages:
  CosmosCore:
    path: Packages/CosmosCore
  CosmosUI:
    path: Packages/CosmosUI
  CosmosIntel:
    path: Packages/CosmosIntel

targets:
  Forge:
    type: application
    platform: iOS
    sources:
      - path: Forge
        excludes:
          - "*.xcassets"
      - path: Forge/Assets.xcassets
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.iroralabs.forge
        PRODUCT_NAME: Forge
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Forge/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        ENABLE_PREVIEWS: "YES"
    dependencies:
      - package: CosmosCore
      - package: CosmosUI
      - package: CosmosIntel
    entitlements:
      path: Forge/Forge.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
